// @generated by protobuf-ts 2.2.2 with parameter generate_dependencies
// @generated from protobuf file "graph.proto" (package "graph", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MESSAGE_TYPE } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Value } from "./google/protobuf/struct";
/**
 * @generated from protobuf message graph.Request
 */
export interface Request {
    /**
     * @generated from protobuf field: string query = 1;
     */
    query: string;
    /**
     * @generated from protobuf field: google.protobuf.Value variable_values = 2;
     */
    variableValues?: Value;
    /**
     * @generated from protobuf field: string operation_name = 3;
     */
    operationName: string;
    /**
     * @generated from protobuf field: bool subscribe = 4;
     */
    subscribe: boolean;
}
/**
 * @generated from protobuf message graph.Result
 */
export interface Result {
    /**
     * @generated from protobuf oneof: data_or_error
     */
    dataOrError: {
        oneofKind: "data";
        /**
         * @generated from protobuf field: google.protobuf.Value data = 1;
         */
        data: Value;
    } | {
        oneofKind: "error";
        /**
         * @generated from protobuf field: google.protobuf.Value error = 2;
         */
        error: Value;
    } | {
        oneofKind: undefined;
    };
}
// @generated message type with reflection information, may provide speed optimized methods
class Request$Type extends MessageType<Request> {
    constructor() {
        super("graph.Request", [
            { no: 1, name: "query", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "variable_values", kind: "message", T: () => Value },
            { no: 3, name: "operation_name", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "subscribe", kind: "scalar", T: 8 /*ScalarType.BOOL*/ }
        ]);
    }
    create(value?: PartialMessage<Request>): Request {
        const message = { query: "", operationName: "", subscribe: false };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<Request>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Request): Request {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string query */ 1:
                    message.query = reader.string();
                    break;
                case /* google.protobuf.Value variable_values */ 2:
                    message.variableValues = Value.internalBinaryRead(reader, reader.uint32(), options, message.variableValues);
                    break;
                case /* string operation_name */ 3:
                    message.operationName = reader.string();
                    break;
                case /* bool subscribe */ 4:
                    message.subscribe = reader.bool();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Request, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string query = 1; */
        if (message.query !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.query);
        /* google.protobuf.Value variable_values = 2; */
        if (message.variableValues)
            Value.internalBinaryWrite(message.variableValues, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* string operation_name = 3; */
        if (message.operationName !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.operationName);
        /* bool subscribe = 4; */
        if (message.subscribe !== false)
            writer.tag(4, WireType.Varint).bool(message.subscribe);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message graph.Request
 */
export const Request = new Request$Type();
// @generated message type with reflection information, may provide speed optimized methods
class Result$Type extends MessageType<Result> {
    constructor() {
        super("graph.Result", [
            { no: 1, name: "data", kind: "message", oneof: "dataOrError", T: () => Value },
            { no: 2, name: "error", kind: "message", oneof: "dataOrError", T: () => Value }
        ]);
    }
    create(value?: PartialMessage<Result>): Result {
        const message = { dataOrError: { oneofKind: undefined } };
        globalThis.Object.defineProperty(message, MESSAGE_TYPE, { enumerable: false, value: this });
        if (value !== undefined)
            reflectionMergePartial<Result>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: Result): Result {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* google.protobuf.Value data */ 1:
                    message.dataOrError = {
                        oneofKind: "data",
                        data: Value.internalBinaryRead(reader, reader.uint32(), options, (message.dataOrError as any).data)
                    };
                    break;
                case /* google.protobuf.Value error */ 2:
                    message.dataOrError = {
                        oneofKind: "error",
                        error: Value.internalBinaryRead(reader, reader.uint32(), options, (message.dataOrError as any).error)
                    };
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: Result, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* google.protobuf.Value data = 1; */
        if (message.dataOrError.oneofKind === "data")
            Value.internalBinaryWrite(message.dataOrError.data, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* google.protobuf.Value error = 2; */
        if (message.dataOrError.oneofKind === "error")
            Value.internalBinaryWrite(message.dataOrError.error, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message graph.Result
 */
export const Result = new Result$Type();
