FROM node:16-alpine AS builder

RUN apk --no-cache --virtual build-dependencies add \
    python2 \
    make \
    g++ \
    git \
    openssh

# Download public key for github.com
RUN mkdir -p /root/.ssh && \
    chmod 0700 /root/.ssh && \
    ssh-keyscan github.com >> /root/.ssh/known_hosts


COPY ./ /opt/box
WORKDIR /opt/box
RUN npm install

CMD ['npm','start']

